# Practical grammar — 22 lessons × 3 quizzes

PRACTICAL: list = [
    (
        "Would you mind",
        "Would you mind + -ing? 정중한 요청.",
        "Would you mind opening the window?",
        "창문 좀 열어 주시겠어요?",
        "거절 시 Not at all / Of course not.",
        [
            ("Would you mind ___ the window?", "opening", ["opening", "open", "to open", "opened"]),
            ("Would you mind if I ___ here?", "sat", ["sat", "sit", "sitting", "sits"]),
            ("Do you mind ___ the music down?", "turning", ["turning", "turn", "to turn", "turned"]),
        ],
    ),
    (
        "Could you",
        "Could you + V? 공손한 부탁.",
        "Could you speak more slowly?",
        "좀 더 천천히 말씀해 주시겠어요?",
        "Could I ~? 도 허락을 구합니다.",
        [
            ("___ you help me?", "Could", ["Could", "Can", "Will", "Do"]),
            ("Could you speak more ___?", "slowly", ["slowly", "slow", "slower", "slowest"]),
            ("___ I use your phone?", "Could", ["Could", "Can", "Will", "Do"]),
        ],
    ),
    (
        "I'd like to",
        "I'd like to + V. 주문·요청.",
        "I'd like to make a reservation.",
        "예약하고 싶습니다.",
        "I'd = I would / I had 맥락에 주의.",
        [
            ("I'd like ___ order pasta.", "to", ["to", "for", "ing", "ed"]),
            ("I'd like a ___, please.", "coffee", ["coffee", "coffees", "coffeed", "coffing"]),
            ("We'd like ___ check in.", "to", ["to", "for", "ing", "on"]),
        ],
    ),
    (
        "Have you ever",
        "Have you ever + p.p.? 경험 질문.",
        "Have you ever tried kimchi?",
        "김치 먹어 본 적 있어요?",
        "Yes, I have / No, I haven't.",
        [
            ("Have you ever ___ abroad?", "been", ["been", "be", "being", "was"]),
            ("___ you ever seen this show?", "Have", ["Have", "Has", "Did", "Do"]),
            ("She has never ___ sushi.", "tried", ["tried", "try", "trying", "tries"]),
        ],
    ),
    (
        "I'd rather",
        "would rather + V. 차라리 ~하다.",
        "I'd rather walk than drive.",
        "운전하기보다 걷는 게 낫습니다.",
        "would rather A than B.",
        [
            ("I'd rather ___ than drive.", "walk", ["walk", "walking", "to walk", "walked"]),
            ("Would you rather ___ or stay?", "go", ["go", "going", "to go", "went"]),
            ("She'd rather not ___ about it.", "talk", ["talk", "talking", "to talk", "talked"]),
        ],
    ),
    (
        "It's time to",
        "It's time to + V / for + 명사.",
        "It's time to leave.",
        "떠날 시간입니다.",
        "It's high time은 가정법 과거도 가능.",
        [
            ("It's time ___ leave.", "to", ["to", "for", "ing", "on"]),
            ("It's time for ___.", "lunch", ["lunch", "lunches", "lunched", "lunching"]),
            ("It's time we ___.", "went", ["went", "go", "going", "goes"]),
        ],
    ),
    (
        "Suggest that",
        "suggest that + (should) + V.",
        "She suggested that we take a taxi.",
        "그녀는 택시를 타자고 제안했다.",
        "suggest + -ing / suggest + 명사도 가능.",
        [
            ("She suggested that we ___ a taxi.", "take", ["take", "takes", "took", "taking"]),
            ("He suggested ___ early.", "leaving", ["leaving", "leave", "to leave", "left"]),
            ("I suggest a ___.", "break", ["break", "breaking", "broke", "breaks"]),
        ],
    ),
    (
        "Apologize for",
        "apologize for + -ing. ~에 대해 사과.",
        "I apologize for being late.",
        "늦어서 죄송합니다.",
        "I'm sorry for ~ 도 같은 의미.",
        [
            ("I apologize for ___ late.", "being", ["being", "be", "to be", "was"]),
            ("She apologized for ___ the mistake.", "making", ["making", "make", "to make", "made"]),
            ("We apologize for the ___.", "delay", ["delay", "delays", "delayed", "delaying"]),
        ],
    ),
    (
        "Look / Sound / Feel",
        "감각동사 + 형용사.",
        "You look tired today.",
        "오늘 피곤해 보여요.",
        "look은 외모·인상입니다.",
        [
            ("You look ___ today.", "tired", ["tired", "tire", "tiring", "tiredly"]),
            ("That sounds ___.", "great", ["great", "greatly", "greatness", "greater"]),
            ("I feel ___.", "better", ["better", "well", "good", "best"]),
        ],
    ),
    (
        "Make / Let / Have",
        "make O V, let O V, have O V.",
        "The news made me happy.",
        "그 소식이 나를 기쁘게 했다.",
        "have O p.p.는 '~하게 시키다(완료)'.",
        [
            ("The news made me ___.", "happy", ["happy", "happily", "happiness", "happier"]),
            ("Let me ___ you.", "help", ["help", "helping", "to help", "helped"]),
            ("I'll have him ___ you.", "call", ["call", "calling", "to call", "called"]),
        ],
    ),
    (
        "In order to",
        "in order to + V: ~하기 위해.",
        "I study in order to pass the test.",
        "시험에 합격하기 위해 공부합니다.",
        "so as to는 격식체.",
        [
            ("I study in order ___ pass.", "to", ["to", "for", "ing", "on"]),
            ("She left early in order ___ catch the train.", "to", ["to", "for", "ing", "on"]),
            ("We save money in order ___ travel.", "to", ["to", "for", "ing", "on"]),
        ],
    ),
    (
        "Despite / In spite of",
        "despite / in spite of + 명사/-ing. ~에도 불구하고.",
        "Despite the rain, we went out.",
        "비에도 불구하고 나갔습니다.",
        "뒤에 문장 전체는 despite the fact that.",
        [
            ("___ the rain, we went out.", "Despite", ["Despite", "Although", "Because", "Since"]),
            ("In spite of ___ tired, she continued.", "being", ["being", "be", "to be", "was"]),
            ("He succeeded despite ___ difficulties.", "many", ["many", "much", "more", "most"]),
        ],
    ),
    (
        "As soon as",
        "as soon as + 절: ~하자마자.",
        "Call me as soon as you arrive.",
        "도착하자마자 전화해 주세요.",
        "when과 비슷하지만 '즉시' 느낌.",
        [
            ("Call me as soon as you ___.", "arrive", ["arrive", "arrives", "arrived", "arriving"]),
            ("As soon as I ___, I will email you.", "finish", ["finish", "finishes", "finished", "finishing"]),
            ("She left as soon as the meeting ___.", "ended", ["ended", "end", "ends", "ending"]),
        ],
    ),
    (
        "Unless",
        "unless = if not. ~하지 않으면.",
        "Unless it rains, we will picnic.",
        "비가 오지 않으면 소풍 갈 거예요.",
        "조건을 나타냅니다.",
        [
            ("___ it rains, we will picnic.", "Unless", ["Unless", "Until", "Although", "Because"]),
            ("You can't enter ___ you have a ticket.", "unless", ["unless", "until", "because", "since"]),
            ("Unless she ___, we will start without her.", "comes", ["comes", "come", "came", "coming"]),
        ],
    ),
    (
        "Whether",
        "whether ~ or not: ~인지 아닌지.",
        "I don't know whether he will come.",
        "그가 올지 모르겠다.",
        "if와 달리 whether는 명확합니다.",
        [
            ("I don't know ___ he will come.", "whether", ["whether", "weather", "if", "that"]),
            ("Tell me ___ you need help.", "if", ["if", "whether", "that", "what"]),
            ("She asked whether I ___ busy.", "was", ["was", "were", "am", "is"]),
        ],
    ),
    (
        "Used to",
        "used to + V: 예전에 ~하곤 했다.",
        "I used to play the piano.",
        "예전에는 피아노를 쳤습니다.",
        "be used to -ing와 구분하세요.",
        [
            ("I ___ to play the piano.", "used", ["used", "use", "using", "uses"]),
            ("She didn't use to ___ coffee.", "drink", ["drink", "drinks", "drinking", "drank"]),
            ("___ you use to live here?", "Did", ["Did", "Do", "Are", "Have"]),
        ],
    ),
    (
        "By the time",
        "by the time + 절: ~할 때쯤에는.",
        "By the time you arrive, I will be ready.",
        "네가 도착할 때쯤이면 준비돼 있을 거야.",
        "미래완료와 자주 연결됩니다.",
        [
            ("By the time you ___, I will be ready.", "arrive", ["arrive", "arrives", "arrived", "arriving"]),
            ("By the time she called, I ___ left.", "had", ["had", "have", "has", "was"]),
            ("By the time we finish, they ___ have eaten.", "will", ["will", "would", "have", "are"]),
        ],
    ),
    (
        "Not only ... but also",
        "not only A but also B.",
        "She is not only smart but also kind.",
        "그녀는 똑똑할 뿐 아니라 친절하다.",
        "강조 구문입니다.",
        [
            ("She is not only smart ___ also kind.", "but", ["but", "and", "or", "so"]),
            ("Not only did he win, ___ he broke a record.", "but", ["but", "and", "or", "so"]),
            ("They not only sell books ___ also coffee.", "but", ["but", "and", "or", "so"]),
        ],
    ),
    (
        "It seems / appears",
        "It seems that / seems to V: ~인 것 같다.",
        "It seems that he is busy.",
        "그가 바쁜 것 같습니다.",
        "seem + 형용사도 가능합니다.",
        [
            ("It ___ that he is busy.", "seems", ["seems", "seem", "seemed", "seeming"]),
            ("She seems ___.", "happy", ["happy", "happily", "happiness", "happier"]),
            ("It appears we ___ late.", "are", ["are", "is", "were", "was"]),
        ],
    ),
    (
        "Suppose / What if",
        "가정·제안: suppose, what if.",
        "What if we leave early?",
        "일찍 떠나면 어때?",
        "Suppose you won the lottery?",
        [
            ("What if we ___ early?", "leave", ["leave", "leaves", "left", "leaving"]),
            ("Suppose it ___ tomorrow?", "rains", ["rains", "rain", "rained", "raining"]),
            ("What if she ___ say no?", "does", ["does", "do", "did", "doing"]),
        ],
    ),
    (
        "No matter",
        "no matter how/what/who: 아무리 ~해도.",
        "No matter how hard I try, I fail.",
        "아무리 노력해도 실패한다.",
        "whatever = no matter what.",
        [
            ("No matter how hard I ___, I fail.", "try", ["try", "tries", "tried", "trying"]),
            ("No matter ___ you say, I won't go.", "what", ["what", "that", "which", "who"]),
            ("___ happens, stay calm.", "Whatever", ["Whatever", "However", "Whoever", "Whichever"]),
        ],
    ),
    (
        "The more ... the more",
        "the + 비교급 ..., the + 비교급 ...",
        "The more you practice, the better you get.",
        "연습할수록 더 나아집니다.",
        "비례 관계를 나타냅니다.",
        [
            ("The more you ___, the better you get.", "practice", ["practice", "practices", "practiced", "practicing"]),
            ("The ___ it rains, the worse traffic is.", "more", ["more", "most", "much", "many"]),
            ("The harder you work, the ___ you succeed.", "more likely", ["more likely", "most likely", "likely", "likelier"]),
        ],
    ),
]
