# Middle school grammar — 30 lessons × 3 quizzes

MIDDLE: list = [
    (
        "be동사 (현재)",
        "I→am, You/We/They→are, He/She/It→is. 부정 isn't/aren't, 의문 Am/Is/Are.",
        "She is a student.",
        "그녀는 학생입니다.",
        "주어와 be동사 짝이 맞아야 합니다.",
        [
            ("She ___ a student.", "is", ["is", "are", "am", "be"]),
            ("They ___ in the library.", "are", ["are", "is", "am", "was"]),
            ("___ you ready?", "Are", ["Are", "Is", "Am", "Do"]),
        ],
    ),
    (
        "일반동사 (현재)",
        "3인칭 단수 -s/-es. 부정 don't/doesn't, 의문 Do/Does + 동사원형.",
        "He plays soccer every Sunday.",
        "그는 매주 일요일 축구를 합니다.",
        "He/She/It 뒤에는 동사에 s를 붙입니다.",
        [
            ("He ___ soccer every Sunday.", "plays", ["plays", "play", "playing", "played"]),
            ("She ___ not like spicy food.", "does", ["does", "do", "is", "has"]),
            ("___ they watch movies on Fridays?", "Do", ["Do", "Does", "Are", "Did"]),
        ],
    ),
    (
        "현재진행",
        "am/is/are + -ing. 지금 하는 일, 임시 상황.",
        "They are studying English now.",
        "그들은 지금 영어를 공부하고 있습니다.",
        "now, at the moment와 자주 씁니다.",
        [
            ("They ___ studying English now.", "are", ["are", "is", "am", "be"]),
            ("I ___ not sleeping.", "am", ["am", "is", "are", "do"]),
            ("What ___ she doing?", "is", ["is", "are", "does", "do"]),
        ],
    ),
    (
        "과거 시제",
        "규칙동사 -ed, 불규칙동사 과거형 암기. did + 동사원형(의문/부정).",
        "I visited Jeju last summer.",
        "나는 지난여름 제주를 방문했습니다.",
        "yesterday, last week 등 과거 표현과 함께 씁니다.",
        [
            ("I ___ Jeju last summer.", "visited", ["visited", "visit", "visiting", "visits"]),
            ("She ___ not go to school yesterday.", "did", ["did", "does", "do", "was"]),
            ("___ you finish your homework?", "Did", ["Did", "Do", "Does", "Are"]),
        ],
    ),
    (
        "과거진행",
        "was/were + -ing. 과거의 특정 시점에 진행 중이던 일.",
        "I was reading when he called.",
        "그가 전화했을 때 나는 읽고 있었습니다.",
        "when + 과거, was/were -ing 구조를 기억하세요.",
        [
            ("I ___ reading when he called.", "was", ["was", "were", "am", "is"]),
            ("They ___ playing at 5 p.m.", "were", ["were", "was", "are", "is"]),
            ("What ___ she doing then?", "was", ["was", "were", "did", "does"]),
        ],
    ),
    (
        "미래 will",
        "will + 동사원형. 갑작스러운 결심, 예측, 약속.",
        "It will rain tomorrow.",
        "내일 비가 올 것입니다.",
        "will은 모든 주어에 같게 씁니다.",
        [
            ("It ___ rain tomorrow.", "will", ["will", "is", "was", "be"]),
            ("I ___ help you with this.", "will", ["will", "am", "was", "do"]),
            ("She ___ not be late.", "won't", ["won't", "isn't", "doesn't", "didn't"]),
        ],
    ),
    (
        "be going to",
        "be going to + 동사원형. 계획, 근거 있는 예측.",
        "We are going to start a club.",
        "우리는 동아리를 시작할 예정입니다.",
        "이미 정해진 계획에 적합합니다.",
        [
            ("We ___ going to start a club.", "are", ["are", "is", "am", "will"]),
            ("He ___ going to visit his grandma.", "is", ["is", "are", "am", "do"]),
            ("They ___ not going to wait.", "are", ["are", "is", "am", "was"]),
        ],
    ),
    (
        "조동사 can",
        "can + 동사원형. 능력, 허가. could는 과거/정중.",
        "You can use my dictionary.",
        "내 사전을 써도 됩니다.",
        "can 뒤에는 항상 동사원형입니다.",
        [
            ("You ___ use my dictionary.", "can", ["can", "cans", "coulds", "are"]),
            ("She ___ speak three languages.", "can", ["can", "cans", "is", "does"]),
            ("___ I sit here?", "Can", ["Can", "Do", "Am", "Will"]),
        ],
    ),
    (
        "must / have to",
        "must: 강한 의무·추측. have to: 외부 규칙·필요.",
        "Students must wear uniforms.",
        "학생들은 교복을 입어야 합니다.",
        "must는 주어에 따라 변하지 않습니다.",
        [
            ("Students ___ wear uniforms.", "must", ["must", "musts", "have", "can"]),
            ("I ___ finish this today.", "have to", ["have to", "has to", "must to", "had"]),
            ("You ___ not smoke here.", "must", ["must", "have", "can", "do"]),
        ],
    ),
    (
        "should / ought to",
        "should: 조언·추천. ought to: ~해야 한다(격식).",
        "You should drink more water.",
        "물을 더 마시는 것이 좋습니다.",
        "조언할 때 should를 자주 씁니다.",
        [
            ("You ___ drink more water.", "should", ["should", "shall", "must", "can"]),
            ("He ___ study harder.", "should", ["should", "must", "can", "will"]),
            ("We ___ leave early.", "should", ["should", "shall", "will", "are"]),
        ],
    ),
    (
        "비교급",
        "형용사/부사 비교급: -er 또는 more. than과 함께.",
        "This book is more interesting than that one.",
        "이 책이 저 책보다 더 재미있습니다.",
        "음절 수에 따라 -er / more를 선택합니다.",
        [
            ("Tom is ___ than Jim.", "taller", ["taller", "tall", "tallest", "more tall"]),
            ("This is ___ difficult than I thought.", "more", ["more", "most", "much", "very"]),
            ("She runs ___ than before.", "faster", ["faster", "fast", "fastest", "more fast"]),
        ],
    ),
    (
        "최상급",
        "the + -est 또는 the most. 범위 안에서 가장 ~",
        "She is the tallest in our class.",
        "그녀는 우리 반에서 가장 키가 큽니다.",
        "최상급 앞에는 보통 the가 붙습니다.",
        [
            ("She is the ___ in our class.", "tallest", ["tallest", "taller", "tall", "most tall"]),
            ("This is the ___ movie I've seen.", "best", ["best", "better", "good", "most good"]),
            ("He is the ___ student here.", "most diligent", ["most diligent", "more diligent", "diligent", "diligenter"]),
        ],
    ),
    (
        "명사 countable",
        "셀 수 있는 명사: a/an, 복수 -s. many, few, a few.",
        "There are many apples on the table.",
        "테이블 위에 사과가 많이 있습니다.",
        "many + 복수명사, much + 불가산을 구분하세요.",
        [
            ("There are ___ apples on the table.", "many", ["many", "much", "a", "an"]),
            ("I have a ___ books.", "few", ["few", "little", "much", "many"]),
            ("How ___ students are there?", "many", ["many", "much", "often", "long"]),
        ],
    ),
    (
        "명사 uncountable",
        "water, information 등. much, little, a piece of.",
        "I need some water.",
        "물이 좀 필요합니다.",
        "불가산 명사에는 a/an을 바로 쓰지 않습니다.",
        [
            ("I don't have ___ money.", "much", ["much", "many", "few", "a"]),
            ("There is ___ milk left.", "little", ["little", "few", "many", "several"]),
            ("Can I have ___ information?", "some", ["some", "a", "many", "few"]),
        ],
    ),
    (
        "관사 a/an/the",
        "a/an: 불특정 단수. the: 특정·유일·알려진 것.",
        "The sun rises in the east.",
        "태양은 동쪽에서 뜹니다.",
        "유일한 것에는 the를 씁니다.",
        [
            ("I saw ___ dog in the park.", "a", ["a", "the", "an", "some"]),
            ("___ sun rises in the east.", "The", ["The", "A", "An", "Some"]),
            ("She is ___ honest person.", "an", ["an", "a", "the", "some"]),
        ],
    ),
    (
        "전치사 in/on/at",
        "in: 안·월·년. on: 날·요일·표면. at: 시각·특정 장소.",
        "The class starts at 9 a.m.",
        "수업은 오전 9시에 시작합니다.",
        "시간 전치사 at, in, on을 구분하세요.",
        [
            ("The class starts ___ 9 a.m.", "at", ["at", "on", "in", "to"]),
            ("I was born ___ May.", "in", ["in", "on", "at", "for"]),
            ("We meet ___ Monday.", "on", ["on", "in", "at", "by"]),
        ],
    ),
    (
        "There is/are",
        "There is + 단수, There are + 복수. '~이 있다'.",
        "There is a park near my house.",
        "우리 집 근처에 공원이 있습니다.",
        "진짜 주어는 there 뒤의 명사입니다.",
        [
            ("There ___ a park near my house.", "is", ["is", "are", "am", "be"]),
            ("There ___ many people here.", "are", ["are", "is", "am", "was"]),
            ("___ there any milk?", "Is", ["Is", "Are", "Do", "Does"]),
        ],
    ),
    (
        "의문사 What/Where",
        "의문사 + do/does/did + 주어 + 동사원형.",
        "Where did you buy this bag?",
        "이 가방 어디서 샀니?",
        "의문사 뒤에는 의문문 어순입니다.",
        [
            ("___ is your name?", "What", ["What", "Where", "When", "Who"]),
            ("___ did you buy this bag?", "Where", ["Where", "What", "When", "Who"]),
            ("___ does she live?", "Where", ["Where", "What", "Who", "Which"]),
        ],
    ),
    (
        "의문사 When/Why/How",
        "When: 시간, Why: 이유, How: 방법·정도.",
        "Why are you late?",
        "왜 늦었니?",
        "How many/much는 수량을 묻습니다.",
        [
            ("___ are you late?", "Why", ["Why", "When", "Where", "What"]),
            ("___ will the meeting start?", "When", ["When", "Why", "Where", "Who"]),
            ("___ do you go to school?", "How", ["How", "What", "Where", "Who"]),
        ],
    ),
    (
        "접속사 and/but/because",
        "and: 나열, but: 대조, because: 이유.",
        "I stayed home because it was cold.",
        "추워서 집에 있었습니다.",
        "because 뒤에는 문장(절)이 옵니다.",
        [
            ("I like tea, ___ I don't like coffee.", "but", ["but", "and", "because", "so"]),
            ("She studied hard, ___ she passed.", "and", ["and", "but", "because", "or"]),
            ("I stayed home ___ it was cold.", "because", ["because", "but", "and", "so"]),
        ],
    ),
    (
        "so / or",
        "so: 결과 '~해서'. or: 선택 '또는'.",
        "I was tired, so I went to bed early.",
        "피곤해서 일찍 잤습니다.",
        "so는 결과를 연결합니다.",
        [
            ("Hurry up, ___ we will be late.", "or", ["or", "and", "but", "so"]),
            ("It rained, ___ the game was canceled.", "so", ["so", "because", "but", "and"]),
            ("You can have tea ___ coffee.", "or", ["or", "and", "but", "so"]),
        ],
    ),
    (
        "to부정사",
        "to + 동사원형. 목적, 의지, 명사적 용법.",
        "I want to learn French.",
        "프랑스어를 배우고 싶습니다.",
        "want/hope/decide + to V 패턴을 익히세요.",
        [
            ("I want ___ learn French.", "to", ["to", "for", "ing", "ed"]),
            ("She decided ___ study abroad.", "to", ["to", "for", "ing", "on"]),
            ("It is important ___ be kind.", "to", ["to", "for", "ing", "that"]),
        ],
    ),
    (
        "동명사",
        "동사-ing가 명사. enjoy/finish/mind + -ing.",
        "She enjoys reading novels.",
        "그녀는 소설 읽기를 즐깁니다.",
        "enjoy 뒤에는 to가 아니라 -ing입니다.",
        [
            ("She enjoys ___ novels.", "reading", ["reading", "read", "to read", "reads"]),
            ("I finished ___ my homework.", "doing", ["doing", "do", "to do", "did"]),
            ("Thank you for ___ me.", "helping", ["helping", "help", "to help", "helped"]),
        ],
    ),
    (
        "현재완료 (경험)",
        "have/has + p.p. ever, never, before.",
        "I have been to London twice.",
        "런던에 두 번 가 본 적이 있다.",
        "과거 시점이 불분명할 때 현재완료를 씁니다.",
        [
            ("I ___ been to London twice.", "have", ["have", "has", "had", "am"]),
            ("She has ___ seen that movie.", "never", ["never", "ever", "already", "yet"]),
            ("Have you ___ eaten sushi?", "ever", ["ever", "never", "yet", "already"]),
        ],
    ),
    (
        "현재완료 (계속)",
        "for/since + have/has + p.p.",
        "She has lived here for ten years.",
        "그녀는 여기서 10년째 살고 있다.",
        "for는 기간, since는 시작 시점입니다.",
        [
            ("She has lived here ___ ten years.", "for", ["for", "since", "during", "from"]),
            ("I have known him ___ 2020.", "since", ["since", "for", "during", "in"]),
            ("They have waited ___ an hour.", "for", ["for", "since", "during", "at"]),
        ],
    ),
    (
        "수동태 (현재)",
        "be + p.p. 행위자는 by + 명사.",
        "English is spoken in many countries.",
        "영어는 많은 나라에서 사용됩니다.",
        "주어가 동작을 받을 때 수동태입니다.",
        [
            ("English ___ spoken in many countries.", "is", ["is", "are", "was", "speaks"]),
            ("The cake ___ made by my mom.", "was", ["was", "is", "were", "made"]),
            ("These letters ___ written in Korean.", "are", ["are", "is", "was", "write"]),
        ],
    ),
    (
        "형용사 vs 부사",
        "형용사는 명사 수식, 부사는 동사·형용사·문장 수식.",
        "He speaks English fluently.",
        "그는 영어를 유창하게 말합니다.",
        "동사를 꾸밀 때는 부사형을 씁니다.",
        [
            ("He speaks English ___.", "fluently", ["fluently", "fluent", "fluency", "more fluent"]),
            ("She is a ___ singer.", "talented", ["talented", "talently", "talent", "talents"]),
            ("They worked ___.", "hard", ["hard", "hardly", "harder", "hardest"]),
        ],
    ),
    (
        "빈도 부사",
        "always, usually, often, sometimes, never. be동사 뒤·일반동사 앞.",
        "I usually drink coffee in the morning.",
        "나는 보통 아침에 커피를 마신다.",
        "never는 부정의 의미를 포함합니다.",
        [
            ("I ___ drink coffee in the morning.", "usually", ["usually", "usual", "use", "using"]),
            ("She is ___ late.", "never", ["never", "ever", "not", "no"]),
            ("They ___ play tennis on Sundays.", "often", ["often", "oftenly", "oft", "sometime"]),
        ],
    ),
    (
        "Some/Any",
        "some: 긍정·제안. any: 부정·의문.",
        "Do you have any questions?",
        "질문 있으세요?",
        "Would you like some ~?는 제안에 some을 씁니다.",
        [
            ("I don't have ___ friends here.", "any", ["any", "some", "many", "much"]),
            ("Would you like ___ water?", "some", ["some", "any", "many", "few"]),
            ("Are there ___ seats left?", "any", ["any", "some", "much", "little"]),
        ],
    ),
    (
        "How many/much",
        "How many + 복수명사, How much + 불가산명사.",
        "How much does it cost?",
        "얼마예요?",
        "many/few는 셀 수 있을 때 씁니다.",
        [
            ("How ___ students are in your class?", "many", ["many", "much", "often", "long"]),
            ("How ___ sugar do you need?", "much", ["much", "many", "often", "far"]),
            ("How ___ is this T-shirt?", "much", ["much", "many", "often", "old"]),
        ],
    ),
    (
        "Let / Let's",
        "Let's + 동사원형. 함께 하자는 제안.",
        "Let's take a break.",
        "잠깐 쉽시다.",
        "Let's = Let us의 줄임말입니다.",
        [
            ("___ take a break.", "Let's", ["Let's", "Let", "Lets", "We're"]),
            ("Let me ___ you.", "help", ["help", "helps", "helping", "to help"]),
            ("Don't let him ___.", "go", ["go", "goes", "going", "went"]),
        ],
    ),
    (
        "be동사 (과거)",
        "I/He/She/It→was, You/We/They→were. 부정 wasn't/weren't.",
        "They were at home yesterday.",
        "그들은 어제 집에 있었습니다.",
        "과거 시점 yesterday, last week와 함께 씁니다.",
        [
            ("I ___ tired last night.", "was", ["was", "were", "am", "is"]),
            ("They ___ at the park.", "were", ["were", "was", "are", "is"]),
            ("___ she happy then?", "Was", ["Was", "Were", "Is", "Did"]),
            ("We ___ not ready.", "were", ["were", "was", "are", "is"]),
            ("He ___ not here yesterday.", "wasn't", ["wasn't", "weren't", "isn't", "didn't"]),
        ],
    ),
    (
        "재귀대명사",
        "myself, yourself, himself, herself, itself, ourselves, themselves.",
        "She taught herself English.",
        "그녀는 스스로 영어를 배웠습니다.",
        "주어와 목적어가 같을 때 재귀대명사를 씁니다.",
        [
            ("He hurt ___ while playing.", "himself", ["himself", "his", "him", "he"]),
            ("We enjoyed ___ at the party.", "ourselves", ["ourselves", "our", "us", "we"]),
            ("Did you make this ___?", "yourself", ["yourself", "your", "you", "yours"]),
            ("The cat cleaned ___.", "itself", ["itself", "its", "it", "it's"]),
            ("They blamed ___.", "themselves", ["themselves", "their", "them", "they"]),
        ],
    ),
    (
        "명령문·청유문",
        "명령: 동사원형. 청유: Let's / Shall we / Why don't we.",
        "Open the window, please.",
        "창문을 열어 주세요.",
        "주어 you는 생략합니다.",
        [
            ("___ quiet, please.", "Be", ["Be", "Are", "Is", "Being"]),
            ("Don't ___ late.", "be", ["be", "are", "is", "being"]),
            ("___ we start now?", "Shall", ["Shall", "Will", "Do", "Are"]),
            ("___ go for a walk.", "Let's", ["Let's", "Let", "Lets", "We"]),
            ("___ touch that wire.", "Don't", ["Don't", "Doesn't", "Didn't", "Not"]),
        ],
    ),
    (
        "부가의문문",
        "긍정문 + 부정 tag / 부정문 + 긍정 tag. 주어·동사 순서 바뀜.",
        "You like music, don't you?",
        "음악 좋아하죠?",
        "tag는 앞 문장의 시제·조동사와 맞춥니다.",
        [
            ("She is kind, ___ she?", "isn't", ["isn't", "doesn't", "wasn't", "aren't"]),
            ("They don't know, ___ they?", "do", ["do", "don't", "did", "are"]),
            ("He can swim, ___ he?", "can't", ["can't", "doesn't", "isn't", "won't"]),
            ("You went home, ___ you?", "didn't", ["didn't", "don't", "weren't", "isn't"]),
            ("We're late, ___ we?", "aren't", ["aren't", "don't", "isn't", "weren't"]),
        ],
    ),
    (
        "지각동사",
        "see/hear/watch + 목적어 + 동사원형/-ing. 느낌·지각.",
        "I saw him cross the street.",
        "나는 그가 길을 건너는 것을 봤다.",
        "원형은 전체 동작, -ing는 진행 중인 모습입니다.",
        [
            ("I heard her ___ the piano.", "play", ["play", "plays", "to play", "played"]),
            ("We watched them ___.", "running", ["running", "run", "to run", "ran"]),
            ("Did you see it ___?", "fall", ["fall", "falls", "to fall", "fell"]),
            ("She felt the floor ___.", "shake", ["shake", "shakes", "shaking", "shook"]),
            ("I noticed him ___ early.", "leave", ["leave", "leaves", "leaving", "left"]),
        ],
    ),
    (
        "4·5형식 문장",
        "4형식: give/tell + 사람 + 것. 5형식: make/find + O + 형용사/to V.",
        "She gave me a book.",
        "그녀는 나에게 책을 주었다.",
        "4형식은 간접목적어+직접목적어 순서가 중요합니다.",
        [
            ("He told ___ the truth.", "us", ["us", "we", "our", "to us"]),
            ("Mom made me ___ my room.", "clean", ["clean", "cleaning", "to clean", "cleaned"]),
            ("I found the test ___.", "easy", ["easy", "easily", "ease", "easier"]),
            ("Can you lend ___ your pen?", "me", ["me", "I", "my", "mine"]),
            ("They kept the door ___.", "open", ["open", "opened", "opening", "opens"]),
        ],
    ),
    (
        "접속사 when·while",
        "when: ~할 때, while: ~하는 동안. 시간의 부사절.",
        "Call me when you arrive.",
        "도착하면 전화해 주세요.",
        "when/while 뒤 절의 시제는 문맥에 맞게 선택합니다.",
        [
            ("I was reading ___ he called.", "when", ["when", "while", "because", "if"]),
            ("___ she was cooking, I set the table.", "While", ["While", "When", "Because", "If"]),
            ("Wash your hands ___ you eat.", "before", ["before", "after", "while", "when"]),
            ("___ I finish, I'll call you.", "When", ["When", "While", "Because", "If"]),
            ("He fell asleep ___ watching TV.", "while", ["while", "when", "because", "if"]),
        ],
    ),
    (
        "접속사 if (조건)",
        "if + 현재: 실제 조건. If it rains, we will stay home.",
        "If you study, you will pass.",
        "공부하면 합격할 거예요.",
        "if절에는 will을 보통 쓰지 않습니다(미래 조건).",
        [
            ("If it ___, we will cancel.", "rains", ["rains", "will rain", "rained", "rain"]),
            ("I will help you if you ___.", "ask", ["ask", "will ask", "asked", "asking"]),
            ("If she ___ busy, call later.", "is", ["is", "will be", "was", "be"]),
            ("What will you do if he ___?", "comes", ["comes", "will come", "came", "come"]),
            ("If they ___ hard, they succeed.", "work", ["work", "will work", "worked", "working"]),
        ],
    ),
    (
        "주격 관계대명사",
        "who(사람), which(사물), that(둘 다). 앞 명사 수식.",
        "The boy who won is my friend.",
        "우승한 소년은 내 친구입니다.",
        "관계대명사 뒤에는 불완전한 절이 옵니다.",
        [
            ("The girl ___ sings well is Lisa.", "who", ["who", "which", "where", "when"]),
            ("This is the book ___ I bought.", "that", ["that", "who", "where", "when"]),
            ("Students ___ study hard succeed.", "who", ["who", "which", "where", "whose"]),
            ("The phone ___ is on the desk is mine.", "that", ["that", "who", "where", "whose"]),
            ("Anyone ___ tries can learn.", "who", ["who", "which", "where", "when"]),
        ],
    ),
    (
        "목적격 관계대명사",
        "the + 명사 + whom/which/that + 주어 + 동사 (that 생략 가능).",
        "The man (whom) I met was kind.",
        "내가 만난 남자는 친절했다.",
        "목적격은 관계대명사가 목적어 역할합니다.",
        [
            ("The movie ___ we watched was fun.", "that", ["that", "who", "where", "when"]),
            ("The teacher ___ I respect retired.", "whom", ["whom", "which", "where", "when"]),
            ("This is the house ___ they built.", "that", ["that", "who", "where", "whose"]),
            ("The friends ___ I invited came.", "that", ["that", "who", "where", "when"]),
            ("The song ___ she sang was popular.", "that", ["that", "who", "where", "whose"]),
        ],
    ),
    (
        "불규칙 과거동사",
        "go→went, see→saw, have→had, make→made, take→took 등.",
        "She went to school by bus.",
        "그녀는 버스로 학교에 갔다.",
        "불규칙 동사는 암기가 필요합니다.",
        [
            ("We ___ to the beach last summer.", "went", ["went", "go", "goes", "going"]),
            ("I ___ a great movie yesterday.", "saw", ["saw", "see", "sees", "seeing"]),
            ("He ___ his homework at night.", "did", ["did", "do", "does", "doing"]),
            ("They ___ a new friend.", "made", ["made", "make", "makes", "making"]),
            ("She ___ the bus at 8.", "took", ["took", "take", "takes", "taking"]),
        ],
    ),
    (
        "to부정사 (부사적)",
        "목적: to V. 결과: too ~ to. 원인: 형용사 + to V.",
        "I came here to study English.",
        "영어 공부하려고 여기 왔습니다.",
        "in order to = to (더 격식).",
        [
            ("She ran fast ___ catch the bus.", "to", ["to", "for", "ing", "ed"]),
            ("This box is too heavy ___.", "to carry", ["to carry", "carrying", "carry", "carried"]),
            ("I'm glad ___ you.", "to see", ["to see", "seeing", "see", "saw"]),
            ("He was surprised ___ the news.", "to hear", ["to hear", "hearing", "hear", "heard"]),
            ("We left early ___ avoid traffic.", "to", ["to", "for", "ing", "on"]),
        ],
    ),
    (
        "현재완료 (완료·결과)",
        "have/has + p.p. just, already, yet. 방금·이미·아직.",
        "I have just finished lunch.",
        "방금 점심을 끝냈습니다.",
        "결과가 지금까지 이어질 때 씁니다.",
        [
            ("She has ___ left.", "already", ["already", "yet", "ever", "never"]),
            ("Have you eaten ___?", "yet", ["yet", "already", "just", "ever"]),
            ("I have ___ started.", "just", ["just", "yet", "ever", "never"]),
            ("They haven't arrived ___.", "yet", ["yet", "already", "just", "ever"]),
            ("He has ___ called back.", "already", ["already", "yet", "ever", "never"]),
        ],
    ),
]
