# Basic grammar — 22 lessons × 3 quizzes

BASIC: list = [
    (
        "인칭대명사",
        "I, you, he, she, it, we, they. 소유: my, your, his, her.",
        "They are my friends.",
        "그들은 내 친구들입니다.",
        "주어 자리에 인칭대명사를 씁니다.",
        [
            ("___ are my friends.", "They", ["They", "Them", "Their", "Theirs"]),
            ("This book is ___.", "mine", ["mine", "my", "me", "I"]),
            ("I gave ___ a gift.", "her", ["her", "she", "hers", "herself"]),
        ],
    ),
    (
        "This/That/These/Those",
        "가까운 것 this/these, 먼 것 that/those.",
        "That is my bag.",
        "저것은 내 가방입니다.",
        "these/those는 복수입니다.",
        [
            ("___ is my bag.", "That", ["That", "This", "These", "Those"]),
            ("___ students are new.", "These", ["These", "This", "Those", "That"]),
            ("___ shoes are too small.", "Those", ["Those", "These", "That", "This"]),
        ],
    ),
    (
        "형용사 위치",
        "형용사는 명사 앞. a beautiful day.",
        "It is a beautiful day.",
        "아름다운 날입니다.",
        "very + 형용사로 정도를 나타냅니다.",
        [
            ("It is a ___ day.", "beautiful", ["beautiful", "beauty", "beautifully", "beautify"]),
            ("She wears a ___ dress.", "red", ["red", "reds", "redden", "redly"]),
            ("He is a ___ man.", "kind", ["kind", "kindly", "kindness", "kinder"]),
        ],
    ),
    (
        "부사 (방법)",
        "동사·형용사·문장을 꾸밈. quickly, well.",
        "He speaks English well.",
        "그는 영어를 잘 말합니다.",
        "well은 형용사 good의 부사형입니다.",
        [
            ("He speaks English ___.", "well", ["well", "good", "better", "best"]),
            ("She runs ___.", "quickly", ["quickly", "quick", "quicker", "quickest"]),
            ("They worked ___.", "hard", ["hard", "hardly", "harder", "hardest"]),
        ],
    ),
    (
        "There is/are",
        "There is + 단수, There are + 복수.",
        "There is a cat on the sofa.",
        "소파 위에 고양이가 있다.",
        "진짜 주어는 there 뒤 명사입니다.",
        [
            ("There ___ a cat on the sofa.", "is", ["is", "are", "am", "be"]),
            ("There ___ two windows.", "are", ["are", "is", "am", "was"]),
            ("___ there any sugar?", "Is", ["Is", "Are", "Do", "Does"]),
        ],
    ),
    (
        "Some/Any",
        "some: 긍정·제안. any: 부정·의문.",
        "Do you have any questions?",
        "질문 있으세요?",
        "Would you like some coffee?",
        [
            ("I don't have ___ money.", "any", ["any", "some", "many", "much"]),
            ("Would you like ___ tea?", "some", ["some", "any", "many", "few"]),
            ("Are there ___ problems?", "any", ["any", "some", "much", "little"]),
        ],
    ),
    (
        "How many / How much",
        "many + 복수, much + 불가산.",
        "How much does it cost?",
        "얼마예요?",
        "How old are you?는 나이를 묻습니다.",
        [
            ("How ___ books do you have?", "many", ["many", "much", "often", "long"]),
            ("How ___ water do you need?", "much", ["much", "many", "often", "far"]),
            ("How ___ is your brother?", "old", ["old", "many", "much", "long"]),
        ],
    ),
    (
        "Let's / Let me",
        "Let's + V: 제안. Let me + V: 허락 요청.",
        "Let's take a break.",
        "잠깐 쉽시다.",
        "Let's = Let us입니다.",
        [
            ("___ take a break.", "Let's", ["Let's", "Let", "Lets", "We're"]),
            ("Let me ___ you.", "help", ["help", "helps", "helping", "to help"]),
            ("Let's not ___ late.", "be", ["be", "are", "is", "being"]),
        ],
    ),
    (
        "Would like",
        "would like to + V. 정중한 희망.",
        "I would like to order pasta.",
        "파스타를 주문하고 싶습니다.",
        "I'd like = I would like.",
        [
            ("I would like ___ order pasta.", "to", ["to", "for", "ing", "ed"]),
            ("Would you like ___ coffee?", "some", ["some", "any", "many", "much"]),
            ("She'd like ___ visit Korea.", "to", ["to", "for", "ing", "on"]),
        ],
    ),
    (
        "Look forward to",
        "look forward to + -ing. ~을 고대하다.",
        "I look forward to meeting you.",
        "당신을 만나기를 고대합니다.",
        "to 뒤에 -ing가 옵니다.",
        [
            ("I look forward to ___ you.", "meeting", ["meeting", "meet", "to meet", "met"]),
            ("We are looking forward to ___ summer.", "having", ["having", "have", "to have", "had"]),
            ("She looks forward to ___ the news.", "hearing", ["hearing", "hear", "to hear", "heard"]),
        ],
    ),
    (
        "Give up",
        "give up + -ing. 포기하다.",
        "Don't give up studying.",
        "공부를 포기하지 마세요.",
        "give up은 구동사입니다.",
        [
            ("Don't give up ___.", "studying", ["studying", "study", "to study", "studied"]),
            ("He gave up ___ smoking.", "trying to quit", ["trying to quit", "try", "to try", "tried"]),
            ("Never give up ___ your dream.", "chasing", ["chasing", "chase", "to chase", "chased"]),
        ],
    ),
    (
        "Have to / Don't have to",
        "have to: ~해야 한다. don't have to: ~할 필요 없다.",
        "You have to wear a seatbelt.",
        "안전벨트를 매야 합니다.",
        "must와 비슷하지만 외부 규칙 느낌입니다.",
        [
            ("You ___ wear a seatbelt.", "have to", ["have to", "has to", "must to", "had"]),
            ("I ___ finish this today.", "have to", ["have to", "has to", "having", "had"]),
            ("You ___ pay if it's free.", "don't have to", ["don't have to", "doesn't have to", "must not", "haven't"]),
        ],
    ),
    (
        "Be used to",
        "be used to + -ing. ~에 익숙하다.",
        "I'm used to getting up early.",
        "일찍 일어나는 것에 익숙합니다.",
        "used to V는 '예전에 ~하곤 했다'와 다릅니다.",
        [
            ("I'm used to ___ up early.", "getting", ["getting", "get", "to get", "got"]),
            ("She isn't used to ___ spicy food.", "eating", ["eating", "eat", "to eat", "ate"]),
            ("Are you used to ___ alone?", "living", ["living", "live", "to live", "lived"]),
        ],
    ),
    (
        "Question tags",
        "부가의문: 앞 문장과 반대, 주어 대명사.",
        "You are tired, aren't you?",
        "피곤하지, 그렇지?",
        "긍정문 뒤에는 부정 tag입니다.",
        [
            ("You are tired, ___ you?", "aren't", ["aren't", "isn't", "don't", "won't"]),
            ("She can swim, ___ she?", "can't", ["can't", "doesn't", "isn't", "won't"]),
            ("They left, ___ they?", "didn't", ["didn't", "don't", "weren't", "haven't"]),
        ],
    ),
    (
        "Both / Either / Neither",
        "both 둘 다, either 둘 중 하나, neither 둘 다 아님.",
        "Neither answer is correct.",
        "두 답 모두 정답이 아니다.",
        "neither는 단수 동사를 씁니다.",
        [
            ("___ of my parents are teachers.", "Both", ["Both", "Either", "Neither", "All"]),
            ("You can take ___ road.", "either", ["either", "both", "neither", "all"]),
            ("___ student passed the test.", "Neither", ["Neither", "Both", "Either", "All"]),
        ],
    ),
    (
        "Each / Every",
        "each: 개별, every: 전체 하나씩.",
        "Every student has a book.",
        "모든 학생이 책을 가지고 있다.",
        "every + 단수 동사입니다.",
        [
            ("___ student has a book.", "Every", ["Every", "Each", "All", "Both"]),
            ("___ of the bags is heavy.", "Each", ["Each", "Every", "All", "Both"]),
            ("I go to the gym ___ week.", "every", ["every", "each", "all", "both"]),
        ],
    ),
    (
        "Much / Many / A lot of",
        "many + 복수, much + 불가산, a lot of 둘 다.",
        "I have a lot of homework.",
        "숙제가 많이 있습니다.",
        "a lot of는 구어에서 자주 씁니다.",
        [
            ("I don't have ___ time.", "much", ["much", "many", "few", "several"]),
            ("There are ___ people.", "many", ["many", "much", "little", "few"]),
            ("She has ___ friends.", "a lot of", ["a lot of", "many", "much", "few"]),
        ],
    ),
    (
        "A few / A little",
        "a few + 복수(긍정), a little + 불가산(긍정).",
        "I have a few questions.",
        "질문이 몇 가지 있습니다.",
        "few/little만 쓰면 부정적입니다.",
        [
            ("I have ___ questions.", "a few", ["a few", "few", "a little", "little"]),
            ("There is ___ milk left.", "a little", ["a little", "little", "a few", "few"]),
            ("___ people came.", "Few", ["Few", "A few", "Little", "A little"]),
        ],
    ),
    (
        "Already / Yet / Still",
        "already: 이미, yet: 아직(의문·부정), still: 여전히.",
        "Have you finished yet?",
        "아직 끝냈니?",
        "still은 동사 앞에 옵니다.",
        [
            ("Have you finished ___?", "yet", ["yet", "already", "still", "just"]),
            ("I have ___ eaten.", "already", ["already", "yet", "still", "ever"]),
            ("She is ___ working.", "still", ["still", "yet", "already", "ever"]),
        ],
    ),
    (
        "Too / Also / As well",
        "too·also·as well: '~도' 추가.",
        "I like coffee, and I like tea too.",
        "커피도 좋아하고 차도 좋아합니다.",
        "too는 주로 문장 끝에 씁니다.",
        [
            ("I like coffee, and I like tea ___.", "too", ["too", "to", "two", "also"]),
            ("She speaks French. She ___ speaks English.", "also", ["also", "too", "either", "as"]),
            ("He is coming ___ .", "as well", ["as well", "too", "also", "either"]),
        ],
    ),
    (
        "Enough",
        "형용사/부사 + enough. enough + 명사.",
        "We don't have enough time.",
        "시간이 충분하지 않습니다.",
        "enough money = 충분한 돈.",
        [
            ("We don't have ___ time.", "enough", ["enough", "many", "much", "few"]),
            ("She is old ___ to drive.", "enough", ["enough", "too", "so", "very"]),
            ("There isn't ___ sugar.", "enough", ["enough", "many", "much", "few"]),
        ],
    ),
    (
        "Comparative with as",
        "as + 형용사 + as: ~만큼 …하다.",
        "He is as tall as his brother.",
        "그는 형만큼 키가 크다.",
        "not as ~ as = less than.",
        [
            ("He is as tall ___ his brother.", "as", ["as", "than", "from", "to"]),
            ("This is not as easy ___ I thought.", "as", ["as", "than", "from", "like"]),
            ("She runs as fast ___ him.", "as", ["as", "than", "from", "to"]),
        ],
    ),
]
