# High school grammar — 28 lessons × 3 quizzes

HIGH: list = [
    (
        "현재완료 (경험)",
        "have/has + p.p. ever, never, before, once, twice.",
        "I have been to London twice.",
        "나는 런던에 두 번 가 본 적이 있다.",
        "특정 과거 시점 없이 경험을 말할 때 씁니다.",
        [
            ("I ___ been to London twice.", "have", ["have", "has", "had", "was"]),
            ("She has ___ finished her essay.", "already", ["already", "yet", "ever", "never"]),
            ("Have you ___ tried this app?", "ever", ["ever", "never", "yet", "already"]),
        ],
    ),
    (
        "현재완료 (계속)",
        "for + 기간, since + 시작점. have/has + p.p.",
        "She has lived here for ten years.",
        "그녀는 여기서 10년째 살고 있다.",
        "still은 '아직도' 계속을 강조합니다.",
        [
            ("She has lived here ___ ten years.", "for", ["for", "since", "during", "from"]),
            ("I have worked here ___ 2019.", "since", ["since", "for", "during", "in"]),
            ("They have ___ been friends.", "always", ["always", "never", "yet", "already"]),
        ],
    ),
    (
        "현재완료 (완료·결과)",
        "just, already, yet. 막·이미·아직.",
        "He has just finished his homework.",
        "그는 방금 숙제를 끝냈다.",
        "yet는 주로 의문·부정문에 씁니다.",
        [
            ("He has ___ finished his homework.", "just", ["just", "yet", "ever", "never"]),
            ("Have you eaten ___?", "yet", ["yet", "just", "already", "ever"]),
            ("I have ___ seen that film.", "already", ["already", "yet", "just", "never"]),
        ],
    ),
    (
        "과거완료",
        "had + p.p. 과거보다 더 이전의 일.",
        "When I arrived, the train had left.",
        "내가 도착했을 때 기차는 이미 떠났다.",
        "과거 사건의 '더 과거'를 나타냅니다.",
        [
            ("When I arrived, the train ___ left.", "had", ["had", "has", "have", "was"]),
            ("She ___ never seen snow before she moved.", "had", ["had", "has", "have", "was"]),
            ("They ___ finished before we came.", "had", ["had", "have", "has", "were"]),
        ],
    ),
    (
        "미래완료",
        "will have + p.p. 미래의 특정 시점까지 완료.",
        "I will have finished by 6 p.m.",
        "오후 6시까지는 끝낼 것이다.",
        "by + 시점과 자주 함께 씁니다.",
        [
            ("I ___ have finished by 6 p.m.", "will", ["will", "would", "have", "am"]),
            ("She ___ have left by then.", "will", ["will", "would", "has", "is"]),
            ("___ you have completed it by Friday?", "Will", ["Will", "Would", "Have", "Did"]),
        ],
    ),
    (
        "수동태 (다양한 시제)",
        "be + p.p. 시제는 be동사에 맞춤.",
        "The letter was written by Tom.",
        "그 편지는 Tom에 의해 쓰였다.",
        "행위자는 by, 도구는 with를 씁니다.",
        [
            ("The letter ___ written by Tom.", "was", ["was", "is", "were", "wrote"]),
            ("English ___ spoken worldwide.", "is", ["is", "are", "was", "speaks"]),
            ("The windows ___ being cleaned.", "are", ["are", "is", "was", "were"]),
        ],
    ),
    (
        "관계대명사 who",
        "사람 선행사 + who (주격/목적격).",
        "The man who called you is my uncle.",
        "너에게 전화한 남자는 내 삼촌이다.",
        "who는 사람을 꾸밉니다.",
        [
            ("The man ___ called you is my uncle.", "who", ["who", "which", "where", "whose"]),
            ("Students ___ study hard succeed.", "who", ["who", "which", "where", "what"]),
            ("I know the girl ___ won the prize.", "who", ["who", "which", "where", "when"]),
        ],
    ),
    (
        "관계대명사 which/that",
        "사물 선행사 + which/that.",
        "This is the book which I recommended.",
        "이것이 내가 추천한 책이다.",
        "that은 사람·사물 모두 가능합니다.",
        [
            ("This is the book ___ I recommended.", "which", ["which", "who", "where", "whose"]),
            ("The phone ___ he bought is new.", "that", ["that", "who", "where", "when"]),
            ("I lost the keys ___ were on the desk.", "that", ["that", "who", "where", "whose"]),
        ],
    ),
    (
        "관계부사 where/when",
        "where: 장소, when: 시간.",
        "I remember the day when we first met.",
        "우리가 처음 만난 날을 기억한다.",
        "관계부사 뒤에는 완전한 절이 옵니다.",
        [
            ("This is the café ___ we met.", "where", ["where", "which", "who", "whose"]),
            ("Do you know the reason ___ he left?", "why", ["why", "where", "which", "who"]),
            ("Summer is the season ___ I travel most.", "when", ["when", "where", "which", "who"]),
        ],
    ),
    (
        "whose",
        "소유를 나타내는 관계대명사 whose.",
        "She has a brother whose hobby is chess.",
        "그녀에게 체스가 취미인 남동생이 있다.",
        "whose + 명사 구조를 기억하세요.",
        [
            ("She met a writer ___ books are famous.", "whose", ["whose", "who", "which", "whom"]),
            ("I know a girl ___ father is a doctor.", "whose", ["whose", "who", "which", "whom"]),
            ("They live in a house ___ roof is red.", "whose", ["whose", "which", "where", "who"]),
        ],
    ),
    (
        "가정법 과거",
        "If + 과거, would/could + 동사원형.",
        "If I had time, I would help you.",
        "시간이 있다면 도와줄 텐데.",
        "현재 사실과 반대인 상황을 가정합니다.",
        [
            ("If I ___ time, I would help you.", "had", ["had", "have", "has", "will have"]),
            ("If she ___ here, she would know.", "were", ["were", "was", "is", "are"]),
            ("I would travel more if I ___ rich.", "were", ["were", "was", "am", "is"]),
        ],
    ),
    (
        "가정법 과거완료",
        "If + had p.p., would have p.p.",
        "If she had studied, she would have passed.",
        "공부했더라면 합격했을 것이다.",
        "과거 사실에 대한 후회·가정입니다.",
        [
            ("If she ___ studied, she would have passed.", "had", ["had", "has", "have", "studies"]),
            ("I would have called if I ___ known.", "had", ["had", "have", "has", "know"]),
            ("If they ___ left earlier, they would have arrived on time.", "had", ["had", "have", "has", "leave"]),
        ],
    ),
    (
        "가정법 미래 (should)",
        "If + should, were to. 만약 ~한다면.",
        "If you should need help, call me.",
        "도움이 필요하면 전화하세요.",
        "should는 공식적·가능성 낮은 가정입니다.",
        [
            ("If you ___ need help, call me.", "should", ["should", "will", "would", "can"]),
            ("If it ___ rain, we will cancel.", "should", ["should", "will", "would", "is"]),
            ("If he ___ arrive late, tell him to wait.", "should", ["should", "will", "would", "can"]),
        ],
    ),
    (
        "분사구문",
        "접속사+주어 생략, -ing/-ed. 부대상황.",
        "Walking down the street, I met an old friend.",
        "거리를 걷다가 옛 친구를 만났다.",
        "주어가 같을 때만 분사구문을 씁니다.",
        [
            ("___ down the street, I met an old friend.", "Walking", ["Walking", "Walked", "Walk", "To walk"]),
            ("___ by the teacher, she felt nervous.", "Asked", ["Asked", "Asking", "Ask", "To ask"]),
            ("___ finished the work, he went home.", "Having", ["Having", "Have", "Had", "Has"]),
        ],
    ),
    (
        "too ~ to",
        "too + 형용사/부사 + to V: 너무 ~해서 …못하다.",
        "The box is too heavy to carry.",
        "그 상자는 너무 무거워서 들 수 없다.",
        "too는 부정적 '과도함'입니다.",
        [
            ("The box is too heavy ___ carry.", "to", ["to", "for", "that", "so"]),
            ("She is too young ___ drive.", "to", ["to", "for", "that", "so"]),
            ("It was too late ___ call him.", "to", ["to", "for", "that", "so"]),
        ],
    ),
    (
        "enough to",
        "형용사/부사 + enough + to V.",
        "She is old enough to vote.",
        "그녀는 투표할 만큼 나이가 들었다.",
        "enough는 형용사 뒤·부사 앞에 옵니다.",
        [
            ("She is old enough ___ vote.", "to", ["to", "for", "that", "so"]),
            ("He ran fast enough ___ win.", "to", ["to", "for", "that", "so"]),
            ("Is it warm enough ___ swim?", "to", ["to", "for", "that", "so"]),
        ],
    ),
    (
        "so ~ that",
        "so + 형용사/부사 + that 절: 너무 ~해서 …하다.",
        "He was so tired that he fell asleep.",
        "그는 너무 피곤해서 잠들었다.",
        "such + 명사 + that 도 비슷합니다.",
        [
            ("He was so tired ___ he fell asleep.", "that", ["that", "to", "for", "so"]),
            ("It was so cold ___ we stayed inside.", "that", ["that", "to", "for", "so"]),
            ("She spoke so fast ___ I couldn't follow.", "that", ["that", "to", "for", "so"]),
        ],
    ),
    (
        "간접의문문",
        "의문사 + 주어 + 동사. know/tell/wonder 뒤.",
        "I don't know where he lives.",
        "그가 어디 사는지 모른다.",
        "의문사 뒤에는 평서문 어순입니다.",
        [
            ("I don't know where he ___.", "lives", ["lives", "live", "living", "lived"]),
            ("Tell me what time the train ___.", "leaves", ["leaves", "leave", "left", "leaving"]),
            ("She asked why I ___ late.", "was", ["was", "were", "am", "is"]),
        ],
    ),
    (
        "It is ~ that 강조",
        "It is/was + 강조부분 + that/who.",
        "It was Tom that broke the window.",
        "창문을 깬 것은 Tom이었다.",
        "강조할 부분을 It is 뒤에 둡니다.",
        [
            ("It was Tom ___ broke the window.", "that", ["that", "who", "which", "where"]),
            ("It is English ___ we study here.", "that", ["that", "who", "which", "where"]),
            ("It was yesterday ___ I met her.", "that", ["that", "when", "where", "who"]),
        ],
    ),
    (
        "도치 (부정어)",
        "Never/Rarely/Seldom + 조동사 + 주어.",
        "Never have I seen such a view.",
        "그런 경치는 본 적이 없다.",
        "강조·문어체 느낌이 있습니다.",
        [
            ("Never ___ I seen such a view.", "have", ["have", "has", "had", "was"]),
            ("Rarely does he ___ on time.", "arrive", ["arrive", "arrives", "arrived", "arriving"]),
            ("Not only did she win, ___ she broke a record.", "but", ["but", "and", "so", "also"]),
        ],
    ),
    (
        "간접화법",
        "말 전달 시 시제·시간·장소 표현이 뒤로.",
        "He said (that) he was tired.",
        "그는 피곤하다고 말했다.",
        "said 뒤 과거는 '당시' 기준입니다.",
        [
            ("He said he ___ tired.", "was", ["was", "is", "are", "be"]),
            ("She told me she ___ come.", "would", ["would", "will", "can", "may"]),
            ("They asked if I ___ help.", "could", ["could", "can", "will", "may"]),
        ],
    ),
    (
        "사역동사 make/let/have",
        "make O V / let O V / have O V.",
        "My mom made me clean my room.",
        "엄마가 방 청소를 시키셨다.",
        "make는 '~하게 만들다', let은 '허락'.",
        [
            ("My mom made me ___ my room.", "clean", ["clean", "cleaning", "to clean", "cleaned"]),
            ("Let me ___ you.", "help", ["help", "helping", "to help", "helped"]),
            ("I had him ___ the report.", "check", ["check", "checking", "to check", "checked"]),
        ],
    ),
    (
        "목적격 보어",
        "find/consider/think O + 형용사/명사.",
        "I find English interesting.",
        "나는 영어가 흥미롭다고 생각한다.",
        "O + OC 구조입니다.",
        [
            ("I find English ___.", "interesting", ["interesting", "interest", "interested", "interestingly"]),
            ("We consider him ___.", "reliable", ["reliable", "rely", "reliably", "reliance"]),
            ("They elected her ___.", "president", ["president", "presidential", "preside", "presiding"]),
        ],
    ),
    (
        "관용 표현 wish",
        "I wish + 과거: 현재 소망. I wish + had p.p.: 과거 후회.",
        "I wish I could speak better English.",
        "영어를 더 잘 말할 수 있으면 좋겠다.",
        "wish 뒤는 가정법 어순입니다.",
        [
            ("I wish I ___ speak better English.", "could", ["could", "can", "will", "may"]),
            ("I wish it ___ not rain tomorrow.", "would", ["would", "will", "can", "may"]),
            ("She wishes she ___ studied harder.", "had", ["had", "has", "have", "studies"]),
        ],
    ),
    (
        "as if / as though",
        "as if + 절: 마치 ~인 것처럼.",
        "He talks as if he knew everything.",
        "그는 모든 것을 아는 것처럼 말한다.",
        "사실과 다를 수 있는 비유입니다.",
        [
            ("He talks as if he ___ everything.", "knew", ["knew", "knows", "know", "known"]),
            ("She looked as though she ___ crying.", "had been", ["had been", "has", "is", "was"]),
            ("It sounds as if it ___ raining.", "were", ["were", "was", "is", "are"]),
        ],
    ),
    (
        "관계사 what",
        "what = the thing(s) which. 명사절.",
        "What he said was surprising.",
        "그가 한 말은 놀라웠다.",
        "what절 전체가 주어·목적어가 됩니다.",
        [
            ("___ he said was surprising.", "What", ["What", "That", "Which", "Who"]),
            ("I don't understand ___ you mean.", "what", ["what", "that", "which", "who"]),
            ("Tell me ___ you need.", "what", ["what", "that", "which", "who"]),
        ],
    ),
    (
        "복합관계사",
        "whoever, whatever, whichever: ~하는 누구/무엇이든.",
        "Take whatever you want.",
        "원하는 것을 가져가세요.",
        "양보·포괄의 의미가 있습니다.",
        [
            ("Take ___ you want.", "whatever", ["whatever", "however", "whoever", "whichever"]),
            ("___ calls, tell them I'm busy.", "Whoever", ["Whoever", "Whatever", "However", "Whichever"]),
            ("Choose ___ color you like.", "whichever", ["whichever", "whatever", "whoever", "however"]),
        ],
    ),
    (
        "동명사 vs to부정사",
        "remember/forget/stop/regret + -ing vs to V 의미 차이.",
        "I remember meeting her before.",
        "전에 그녀를 만난 것을 기억한다.",
        "의미가 달라지는 동사를 정리하세요.",
        [
            ("I remember ___ her before.", "meeting", ["meeting", "meet", "to meet", "met"]),
            ("He stopped ___ smoke.", "smoking", ["smoking", "smoke", "to smoke", "smoked"]),
            ("She forgot ___ the door.", "to lock", ["to lock", "locking", "lock", "locked"]),
        ],
    ),
    (
        "가정법 혼합",
        "If I had known, I would help you now. 과거 가정 + 현재 결과.",
        "If I had studied harder, I would be relaxed now.",
        "더 공부했더라면 지금은 여유로울 텐데.",
        "과거 가정 + 현재 결과를 연결합니다.",
        [
            ("If I ___ known, I would help you now.", "had", ["had", "have", "has", "know"]),
            ("If she were here, she ___ have agreed.", "would", ["would", "will", "can", "may"]),
            ("If they ___ studied, they would be relaxed now.", "had", ["had", "have", "has", "study"]),
        ],
    ),
    (
        "주어-동사 수 일치",
        "주어가 단수면 동사 단수, 복수면 복수. There is/are, each/every + 단수.",
        "Each of the students has a book.",
        "학생 각각이 책을 가지고 있다.",
        "수식어구가 길어도 동사는 주어와 맞춥니다.",
        [
            ("The list of names ___ on the desk.", "is", ["is", "are", "were", "have"]),
            ("One of my friends ___ sick.", "is", ["is", "are", "were", "have"]),
            ("There ___ many reasons.", "are", ["are", "is", "was", "be"]),
            ("Everybody ___ ready.", "is", ["is", "are", "were", "have"]),
            ("The news ___ surprising.", "is", ["is", "are", "were", "have"]),
        ],
    ),
    (
        "대명사 일치",
        "선행사와 대명사·관계사의 수·인칭 일치. it/they, his/her/their.",
        "If a student fails, he or she must retake.",
        "학생이 떨어지면 재시험을 봐야 한다.",
        "every + 단수 대명사가 흔합니다.",
        [
            ("Each student must bring ___ own lunch.", "his or her", ["his or her", "their", "its", "our"]),
            ("The students said ___ would come.", "they", ["they", "he", "it", "she"]),
            ("Someone left ___ bag.", "his or her", ["his or her", "their", "its", "our"]),
            ("The team won ___ first game.", "its", ["its", "their", "his", "her"]),
            ("Neither Tom nor Jerry ___ late.", "was", ["was", "were", "are", "is"]),
        ],
    ),
    (
        "병렬 구조",
        "and/or/both A and B: 같은 품사·형태 나열.",
        "She likes reading, writing, and drawing.",
        "그녀는 읽기, 쓰기, 그리기를 좋아한다.",
        "not only A but also B도 병렬입니다.",
        [
            ("He wants to travel, ___, and relax.", "study", ["study", "studying", "studied", "studies"]),
            ("The job requires skill, ___, and patience.", "experience", ["experience", "experienced", "experiencing", "experiences"]),
            ("She is smart, kind, and ___.", "funny", ["funny", "fun", "funnily", "funnier"]),
            ("I can neither sing ___ dance.", "nor", ["nor", "or", "and", "but"]),
            ("Not only did he win, ___ he broke a record.", "but", ["but", "and", "or", "so"]),
        ],
    ),
    (
        "현재완료진행",
        "have/has been + -ing. ~해 오고 있다.",
        "I have been studying for two hours.",
        "두 시간째 공부하고 있습니다.",
        "for/since와 자주 씁니다.",
        [
            ("She has been ___ all morning.", "working", ["working", "work", "worked", "works"]),
            ("How long ___ you been waiting?", "have", ["have", "has", "did", "are"]),
            ("They have ___ been friends since 2010.", "been", ["been", "be", "being", "was"]),
            ("It has been ___ for hours.", "raining", ["raining", "rain", "rained", "rains"]),
            ("I have not been ___ well.", "feeling", ["feeling", "feel", "felt", "feels"]),
        ],
    ),
    (
        "조동사 + have p.p.",
        "should/could/might have + p.p. 과거에 대한 추측·후회.",
        "You should have told me earlier.",
        "더 일찍 말해 줬어야 했어.",
        "could have = ~할 수도 있었다(안 함).",
        [
            ("You ___ have called me.", "should", ["should", "will", "can", "may"]),
            ("She ___ have forgotten.", "might", ["might", "will", "can", "must"]),
            ("He ___ have been tired.", "must", ["must", "will", "can", "may"]),
            ("We ___ have left earlier.", "could", ["could", "will", "can", "must"]),
            ("They ___ not have known.", "might", ["might", "will", "can", "must"]),
        ],
    ),
    (
        "현재·과거 분사",
        "현재분사 -ing: 능동·진행. 과거분사 p.p.: 수동·완료.",
        "The broken window needs repair.",
        "깨진 창문은 수리가 필요하다.",
        "분사구문은 주어 생략이 많습니다.",
        [
            ("The girl ___ in red is my sister.", "dressed", ["dressed", "dressing", "dress", "dresses"]),
            ("___ from the hill, we saw the sea.", "Standing", ["Standing", "Stood", "Stand", "Stands"]),
            ("Written in 1990, the book is still popular.", "Written", ["Written", "Writing", "Write", "Writes"]),
            ("The ___ students waited outside.", "excited", ["excited", "exciting", "excite", "excites"]),
            ("___ tired, he went to bed.", "Feeling", ["Feeling", "Felt", "Feel", "Feels"]),
        ],
    ),
    (
        "관계대명사 생략",
        "목적격 that/whom/which 생략 가능. the book (that) I read.",
        "This is the song I love.",
        "이게 내가 좋아하는 노래야.",
        "주격 관계대명사는 생략하지 않습니다.",
        [
            ("The man ___ I met was friendly.", "that", ["that", "who", "where", "when"]),
            ("Everything ___ he said was true.", "that", ["that", "who", "where", "whose"]),
            ("The place ___ we visited was beautiful.", "that", ["that", "who", "whose", "when"]),
            ("The reason ___ he left is unclear.", "why", ["why", "which", "who", "where"]),
            ("The way ___ she sings is unique.", "that", ["that", "who", "where", "when"]),
        ],
    ),
    (
        "Not only 도치",
        "Not only + 조동사/동사 + 주어. 강조 도치.",
        "Not only did he apologize, but he also helped.",
        "그는 사과할 뿐 아니라 도와주기도 했다.",
        "부정어·Not only 뒤에는 의문문 어순입니다.",
        [
            ("Not only ___ she sing, but she also dances.", "does", ["does", "do", "did", "is"]),
            ("Never ___ I seen such a view.", "have", ["have", "has", "had", "do"]),
            ("Hardly ___ he arrived when it rained.", "had", ["had", "has", "have", "was"]),
            ("Seldom ___ we eat out.", "do", ["do", "does", "did", "are"]),
            ("Not only was it cheap, ___ it was good.", "but", ["but", "and", "or", "so"]),
        ],
    ),
    (
        "준동사 (명사적)",
        "to V / V-ing가 주어·목적어·보어. 동사가 아닌 명사 역할.",
        "To err is human.",
        "실수는 인간의 본성이다.",
        "it is ~ to V에서 to부정사가 진주어입니다.",
        [
            ("___ English takes time.", "Learning", ["Learning", "Learn", "To learn", "Learned"]),
            ("It is important ___ polite.", "to be", ["to be", "being", "be", "been"]),
            ("She enjoys ___ novels.", "reading", ["reading", "read", "to read", "reads"]),
            ("His dream is ___ a doctor.", "to become", ["to become", "becoming", "become", "became"]),
            ("I want ___ home early.", "to go", ["to go", "going", "go", "went"]),
        ],
    ),
    (
        "형용사 + 전치사",
        "afraid of, good at, interested in, tired of, famous for.",
        "She is good at math.",
        "그녀는 수학을 잘한다.",
        "형용사마다 어울리는 전치사가 정해져 있습니다.",
        [
            ("He is afraid ___ dogs.", "of", ["of", "at", "in", "for"]),
            ("I'm interested ___ science.", "in", ["in", "on", "at", "for"]),
            ("They are tired ___ waiting.", "of", ["of", "from", "at", "in"]),
            ("She is famous ___ her songs.", "for", ["for", "of", "at", "in"]),
            ("We are proud ___ our team.", "of", ["of", "for", "at", "in"]),
        ],
    ),
]
